minVersion: '2.21.1'
changelog:
  policy: auto
versioning:
  policy: auto
preReleaseCommand: bash -c 'npm version $CRAFT_NEW_VERSION --no-git-tag-version && git add .'
artifactProvider:
  name: none
targets:
  - name: github
